title: Jeremy Seeman's Page
email: jhseeman@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  A CV / portfolio page for Jeremy Seeman.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.drjeremyseeman.com # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jhseeman

# Build settings
remote_theme: "eliottvincent/bay"
plugins:
  - jekyll-feed

header:
  pages:
    - name: Home
      slug: /     
    - name: Research 
  
footer:
  show_powered_by: false
  contact:
    - type: email
      name: Email
      value: jhseeman@umich.edu
  follow:
    - type: googlescholar
      name: GoogleScholar
      link: https://scholar.google.com/citations?hl=en&user=ER77VlIAAAAJ&view_op=list_works&sortby=pubdate
    - type: arxiv
      name: arXiv
      link: https://arxiv.org/search/?query=jeremy+seeman&searchtype=all&source=header
    - type: ssrn
      name: SSRN
      link: https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=5163284
    - type: github
      name: GitHub
      link: http://github.com/jhseeman
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/jeremy-seeman-b8b79ab6
    - type: orcid
      name: ORCID
      link: https://orcid.org/0000-0003-3526-3209
